version: 2.1

jobs:
  Bump Git Tag:
    docker:
      - image: gcr.io/rxjs-fiddle/ci/gitversion:0.0.8
        auth:
          username: _json_key
          password: ${GCLOUD_SERVICE_KEY}

    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:36:c9:3d:00:7e:38:2e:f9:90:10:99:3d:86:64:1c"
      - checkout
      - run: gitversion bump auto
      - run: git push origin --tags

  Build All Images:
    parameters:
      tag:
        type: string
        default: latest
      push:
        type: boolean
        default: false

    docker:
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: echo "${GCLOUD_SERVICE_KEY}" | docker login -u _json_key --password-stdin https://gcr.io
      - run: docker build -t gcr.io/rxjs-fiddle/ci/gcloud:<< parameters.tag >> -f Dockerfile.gcloud .
      - run: docker build -t gcr.io/rxjs-fiddle/ci/gitversion:<< parameters.tag >> -f Dockerfile.gitversion .
      - when:
        condition: << parameters.push >>
        steps:
          - run: docker push gcr.io/rxjs-fiddle/ci/gcloud:<< parameters.tag >>
          - run: docker push gcr.io/rxjs-fiddle/ci/gitversion:<< parameters.tag >>

workflows:
  Tag Commits to Master:
    jobs:
      - Bump Git Tag:
          filters:
            branches:
              only: master

  Build Images for PR Branches:
    jobs:
      - Build All Images:
          filters:
            branches:
              ignore: master

  Push Images for Tags:
    jobs:
      - Build All Images:
          push: true
          tag: ${CIRCLE_TAG}
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
