version: 2
jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker Login
          command: docker login -u _json_key -p ${GCLOUD_SERVICE_KEY} https://us.gcr.io
